export const GET_GISTS_REQUEST_ACTION = "GISTS::GET_GISTS_REQUEST_ACTION";

export const GET_GISTS_SUCCESS_ACTION = "GISTS::GET_GISTS_SUCCESS_ACTION";

export const GET_GISTS_ERROR_ACTION = "GISTS::GET_GISTS_ERROR_ACTION";

export const GET_GISTS_COMPLETE_ACTION = "GISTS::GET_GISTS_COMPLETE_ACTION";
